
function inicio(){
    document.getElementById("portada").style.display="block";
    document.getElementById("ejer1").style.display="none";
    document.getElementById("ejer2").style.display="none";
    document.getElementById("ejer3").style.display="none";
    document.getElementById("ejer4").style.display="none";
    document.getElementById("ejer5").style.display="none";
    document.getElementById("ejer6").style.display="none";
    document.getElementById("ejer7").style.display="none";
    document.getElementById("ejer8").style.display="none";
    document.getElementById("ejer9").style.display="none";
    document.getElementById("ejer10").style.display="none";
    document.getElementById("ejer11").style.display="none";
    document.getElementById("ejer12").style.display="none";
    document.getElementById("ejer13").style.display="none"
}
function ejercicio1(){
    document.getElementById("portada").style.display="none";
    document.getElementById("ejer1").style.display="block";
    document.getElementById("ejer2").style.display="none";
    document.getElementById("ejer3").style.display="none";
    document.getElementById("ejer4").style.display="none";
    document.getElementById("ejer5").style.display="none";
    document.getElementById("ejer6").style.display="none";
    document.getElementById("ejer7").style.display="none";
    document.getElementById("ejer8").style.display="none";
    document.getElementById("ejer9").style.display="none";
    document.getElementById("ejer10").style.display="none";
    document.getElementById("ejer11").style.display="none";
    document.getElementById("ejer12").style.display="none";
    document.getElementById("ejer13").style.display="none"
}
function ejercicio2(){
    document.getElementById("portada").style.display="none";
    document.getElementById("ejer1").style.display="none";
    document.getElementById("ejer2").style.display="block";
    document.getElementById("ejer3").style.display="none";
    document.getElementById("ejer4").style.display="none";
    document.getElementById("ejer5").style.display="none";
    document.getElementById("ejer6").style.display="none";
    document.getElementById("ejer7").style.display="none";
    document.getElementById("ejer8").style.display="none";
    document.getElementById("ejer9").style.display="none";
    document.getElementById("ejer10").style.display="none";
    document.getElementById("ejer11").style.display="none";
    document.getElementById("ejer12").style.display="none";
    document.getElementById("ejer13").style.display="none"
}
function ejercicio3(){
    document.getElementById("portada").style.display="none";
    document.getElementById("ejer1").style.display="none";
    document.getElementById("ejer2").style.display="none";
    document.getElementById("ejer3").style.display="block";
    document.getElementById("ejer4").style.display="none";
    document.getElementById("ejer5").style.display="none";
    document.getElementById("ejer6").style.display="none";
    document.getElementById("ejer7").style.display="none";
    document.getElementById("ejer8").style.display="none";
    document.getElementById("ejer9").style.display="none";
    document.getElementById("ejer10").style.display="none";
    document.getElementById("ejer11").style.display="none";
    document.getElementById("ejer12").style.display="none";
    document.getElementById("ejer13").style.display="none";
}
function ejercicio4(){
    document.getElementById("portada").style.display="none";
    document.getElementById("ejer1").style.display="none";
    document.getElementById("ejer2").style.display="none";
    document.getElementById("ejer3").style.display="none";
    document.getElementById("ejer4").style.display="block";
    document.getElementById("ejer5").style.display="none";
    document.getElementById("ejer6").style.display="none";
    document.getElementById("ejer7").style.display="none";
    document.getElementById("ejer8").style.display="none";
    document.getElementById("ejer9").style.display="none";
    document.getElementById("ejer10").style.display="none";
    document.getElementById("ejer11").style.display="none";
    document.getElementById("ejer12").style.display="none";
    document.getElementById("ejer13").style.display="none";
}
function ejercicio5(){
    document.getElementById("portada").style.display="none";
    document.getElementById("ejer1").style.display="none";
    document.getElementById("ejer2").style.display="none";
    document.getElementById("ejer3").style.display="none";
    document.getElementById("ejer4").style.display="none";
    document.getElementById("ejer5").style.display="block";
    document.getElementById("ejer6").style.display="none";
    document.getElementById("ejer7").style.display="none";
    document.getElementById("ejer8").style.display="none";
    document.getElementById("ejer9").style.display="none";
    document.getElementById("ejer10").style.display="none";
    document.getElementById("ejer11").style.display="none";
    document.getElementById("ejer12").style.display="none";
    document.getElementById("ejer13").style.display="none";
}
function ejercicio6(){
    document.getElementById("portada").style.display="none";
    document.getElementById("ejer1").style.display="none";
    document.getElementById("ejer2").style.display="none";
    document.getElementById("ejer3").style.display="none";
    document.getElementById("ejer4").style.display="none";
    document.getElementById("ejer5").style.display="none";
    document.getElementById("ejer6").style.display="block";
    document.getElementById("ejer7").style.display="none";
    document.getElementById("ejer8").style.display="none";
    document.getElementById("ejer9").style.display="none";
    document.getElementById("ejer10").style.display="none";
    document.getElementById("ejer11").style.display="none";
    document.getElementById("ejer12").style.display="none";
    document.getElementById("ejer13").style.display="none";
}
function ejercicio7(){
    document.getElementById("portada").style.display="none";
    document.getElementById("ejer1").style.display="none";
    document.getElementById("ejer2").style.display="none";
    document.getElementById("ejer3").style.display="none";
    document.getElementById("ejer4").style.display="none";
    document.getElementById("ejer5").style.display="none";
    document.getElementById("ejer6").style.display="none";
    document.getElementById("ejer7").style.display="block";
    document.getElementById("ejer8").style.display="none";
    document.getElementById("ejer9").style.display="none";
    document.getElementById("ejer10").style.display="none";
    document.getElementById("ejer11").style.display="none";
    document.getElementById("ejer12").style.display="none";
    document.getElementById("ejer13").style.display="none";
}
function ejercicio8(){
    document.getElementById("portada").style.display="none";
    document.getElementById("ejer1").style.display="none";
    document.getElementById("ejer2").style.display="none";
    document.getElementById("ejer3").style.display="none";
    document.getElementById("ejer4").style.display="none";
    document.getElementById("ejer5").style.display="none";
    document.getElementById("ejer6").style.display="none";
    document.getElementById("ejer7").style.display="none";
    document.getElementById("ejer8").style.display="block";
    document.getElementById("ejer9").style.display="none";
    document.getElementById("ejer10").style.display="none";
    document.getElementById("ejer11").style.display="none";
    document.getElementById("ejer12").style.display="none";
    document.getElementById("ejer13").style.display="none";
}
function ejercicio9(){
    document.getElementById("portada").style.display="none";
    document.getElementById("ejer1").style.display="none";
    document.getElementById("ejer2").style.display="none";
    document.getElementById("ejer3").style.display="none";
    document.getElementById("ejer4").style.display="none";
    document.getElementById("ejer5").style.display="none";
    document.getElementById("ejer6").style.display="none";
    document.getElementById("ejer7").style.display="none";
    document.getElementById("ejer8").style.display="none";
    document.getElementById("ejer9").style.display="block";
    document.getElementById("ejer10").style.display="none";
    document.getElementById("ejer11").style.display="none";
    document.getElementById("ejer12").style.display="none";
    document.getElementById("ejer13").style.display="none";
}
function ejercicio10(){
    document.getElementById("portada").style.display="none";
    document.getElementById("ejer1").style.display="none";
    document.getElementById("ejer2").style.display="none";
    document.getElementById("ejer3").style.display="none";
    document.getElementById("ejer4").style.display="none";
    document.getElementById("ejer5").style.display="none";
    document.getElementById("ejer6").style.display="none";
    document.getElementById("ejer7").style.display="none";
    document.getElementById("ejer8").style.display="none";
    document.getElementById("ejer9").style.display="none";
    document.getElementById("ejer10").style.display="block";
    document.getElementById("ejer11").style.display="none";
    document.getElementById("ejer12").style.display="none";
    document.getElementById("ejer13").style.display="none";
}
function ejercicio11(){
    document.getElementById("portada").style.display="none";
    document.getElementById("ejer1").style.display="none";
    document.getElementById("ejer2").style.display="none";
    document.getElementById("ejer3").style.display="none";
    document.getElementById("ejer4").style.display="none";
    document.getElementById("ejer5").style.display="none";
    document.getElementById("ejer6").style.display="none";
    document.getElementById("ejer7").style.display="none";
    document.getElementById("ejer8").style.display="none";
    document.getElementById("ejer9").style.display="none";
    document.getElementById("ejer10").style.display="none";
    document.getElementById("ejer11").style.display="block";
    document.getElementById("ejer12").style.display="none";
    document.getElementById("ejer13").style.display="none";
}
function ejercicio12(){
    document.getElementById("portada").style.display="none";
    document.getElementById("ejer1").style.display="none";
    document.getElementById("ejer2").style.display="none";
    document.getElementById("ejer3").style.display="none";
    document.getElementById("ejer4").style.display="none";
    document.getElementById("ejer5").style.display="none";
    document.getElementById("ejer6").style.display="none";
    document.getElementById("ejer7").style.display="none";
    document.getElementById("ejer8").style.display="none";
    document.getElementById("ejer9").style.display="none";
    document.getElementById("ejer10").style.display="none";
    document.getElementById("ejer11").style.display="none";
    document.getElementById("ejer12").style.display="block";
    document.getElementById("ejer13").style.display="none";
}
function ejercicio13(){
    document.getElementById("portada").style.display="none";
    document.getElementById("ejer1").style.display="none";
    document.getElementById("ejer2").style.display="none";
    document.getElementById("ejer3").style.display="none";
    document.getElementById("ejer4").style.display="none";
    document.getElementById("ejer5").style.display="none";
    document.getElementById("ejer6").style.display="none";
    document.getElementById("ejer7").style.display="none";
    document.getElementById("ejer8").style.display="none";
    document.getElementById("ejer9").style.display="none";
    document.getElementById("ejer10").style.display="none";
    document.getElementById("ejer11").style.display="none";
    document.getElementById("ejer12").style.display="none";
    document.getElementById("ejer13").style.display="block";
}
function frente(){
    document.getElementById("carousel").style.display="block";
    document.getElementById("tr").style.display="none";
    document.getElementById("cr").style.display="none"; 
}
function triangulo(){
    document.getElementById("carousel").style.display="none";
    document.getElementById("tr").style.display="block";
    document.getElementById("cr").style.display="none";
}
function circulo(){
    document.getElementById("carousel").style.display="none";
    document.getElementById("tr").style.display="none";
    document.getElementById("cr").style.display="block";
}


function empresa(){
    document.getElementById("img").style.display="block";
    document.getElementById("gerente").style.display="none";
    document.getElementById("trabajador").style.display="none";
}
function gerente(){
    document.getElementById("img").style.display="none";
    document.getElementById("gerente").style.display="block";
    document.getElementById("trabajador").style.display="none";
}
function trabajador(){
    document.getElementById("img").style.display="none";
    document.getElementById("gerente").style.display="none";
    document.getElementById("trabajador").style.display="block"; 
}
